services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    ports:
      - 8000:8000
    volumes:
      - ./php/src:/var/www/html/backend
      - ./Next:/var/www/html/frontend
  web:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./php/src:/var/www/html/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
